# Uncomment the next line to define a global platform for your project
platform :ios, '14.5'

target 'NHBankFundManagemnet' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SwiftyGif'

  # Pods for NHBankFundManagemnet

  target 'NHBankFundManagemnetTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NHBankFundManagemnetUITests' do
    # Pods for testing
  end

end
